version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_DATABASE=tolmach
      - MYSQL_USER=tolmach
      - MYSQL_PASSWORD=yRqUxdGIOXikrnzlLcGl
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - my-network-name

  elastic:
    image: elasticsearch:2.4.6-alpine
    depends_on:
      - db
    networks:
      - my-network-name

  redis:
    image: redis
    networks:
      - my-network-name

  app:
    build: ../django
    volumes:
      - ../django:/var/www/tolma.ch
      - ./volumes/logs:/var/log/tolma.ch
      - ./volumes/docs:/var/www/tolmach_documents
      - ./volumes/static:/var/www/tolma.ch/static
      - ./volumes/media:/var/www/tolma.ch/media
    environment:
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - my-network-name

  nginx:
    build: ./nginx
    volumes:
      - ./volumes/logs:/var/log/tolma.ch
      - ./volumes/static:/var/www/tolma.ch/static
      - ./volumes/media:/var/www/tolma.ch/media
    ports:
    - 80:80
    - 443:443
    depends_on:
      - app
    networks:
      - my-network-name

  lt:
    image: silviof/docker-languagetool
    networks:
      - my-network-name

networks:
  my-network-name:
    driver: bridge